name: Run CI

on: [push]

env:
  CI_POETRY_VERSION: '1.6.1'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out source tree
        uses: actions/checkout@v3

      - name: Load cached Poetry installation
        id: load-cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-release-v${{ env.CI_POETRY_VERSION }}

      - name: Update PATH
        if: steps.load-cached-poetry.outputs.cache-hit == 'true'
        run: |-
          echo ~/.local/bin >> ${GITHUB_PATH}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        if: steps.load-cached-poetry.outputs.cache-hit != 'true'
        with:
          version: ${{ env.CI_POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Use specified Python version
        uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version-file: .python-version

      - name: Install dependencies
        # See also:
        # https://github.com/python-poetry/poetry/issues/7184
        run: poetry install --no-ansi --no-interaction --no-root

      - name: Install target package
        run: poetry install --no-ansi --no-interaction

      - name: Run static typechecking
        run: poetry run poe typecheck

      - name: Run linter
        run: poetry run poe linter

      - name: Run unit tests
        run: poetry run poe tests
